# Altrua
[[redirects]]
  from = "/"
  to = "https://www.grassrootslabs.com/altrua-health-share-members"
  status = 302
  conditions = { Host = "altrua.grassrootslabs.com" }

[[redirects]]
  from = "/*"
  to = "https://www.grassrootslabs.com/altrua-health-share-members"
  status = 302
  conditions = { Host = "altrua.grassrootslabs.com" }

# Providers
[[redirects]]
  from = "/"
  to = "https://www.grassrootslabs.com/Physician%20Offices%20&%20Provider%20Groups"
  status = 302
  conditions = { Host = "providers.grassrootslabs.com" }

[[redirects]]
  from = "/*"
  to = "https://www.grassrootslabs.com/Physician%20Offices%20&%20Provider%20Groups"
  status = 302
  conditions = { Host = "providers.grassrootslabs.com" }

# Medi-Share
[[redirects]]
  from = "/"
  to = "https://www.grassrootslabs.com/medi-share-members"
  status = 302
  conditions = { Host = "medi-share.grassrootslabs.com" }

[[redirects]]
  from = "/*"
  to = "https://www.grassrootslabs.com/medi-share-members"
  status = 302
  conditions = { Host = "medi-share.grassrootslabs.com" }

# Final fallback for all others — must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
