# Altrua root
[[redirects]]
from = "/"
to = "https://www.grassrootslabs.com/altrua-health-share-members"
status = 302
conditions = { Host = "altrua.grassrootslabs.com" }

# Medi-Share root
[[redirects]]
from = "/"
to = "https://www.grassrootslabs.com/medi-share-members"
status = 302
conditions = { Host = "medi-share.grassrootslabs.com" }

# Providers root
[[redirects]]
from = "/"
to = "https://www.grassrootslabs.com/Physician%20Offices%20&%20Provider%20Groups"
status = 302
conditions = { Host = "providers.grassrootslabs.com" }
